--- #YAML:1.0
name:               SWISH-Prog-Lucy
version:            0.06
abstract:           Swish3 Apache Lucy backend
author:
    - Peter Karman <karman at cpan dot org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Lucy:                 0.002001
    LucyX::Search::WildcardQuery:  0.02
    Path::Class::File::Lockable:  0
    Path::Class::File::Stat:  0.03
    perl:                 5.008003
    Search::Query:        0.17
    Search::Query::Dialect::Lucy:  0.03
    Sort::SQL:            0.06
    SWISH::3:             1
    SWISH::Prog:          0.53
    Test::More:           0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=SWISH-Prog-Lucy
    homepage:    http://dev.swish-e.org/wiki/perl
    license:     http://dev.perl.org/licenses/
    repository:  http://svn.swish-e.org/perl/SWISH-Prog-Lucy/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
